import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="Indu@5812",
  db="fruit"
)
mycursor = mydb.cursor()
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(1001,1000,'Banana',20,1)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(1002,1000,'Orange',10,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(1003,1000,'Apple',15,5)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(1004,1000,'Watermelon',25,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(1005,1000,'Papaya',20,8)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(1006,1000,'Mango',50,15)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(1007,1000,'PineApple',15,20)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(1008,1000,'Pomegranate',20,12)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(1009,1000,'Guava',20,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(2001,2000,'Banana',20,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(2002,2000,'Orange',10,1)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(2003,2000,'Apple',15,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(2004,2000,'Watermelon',25,15)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(2005,2000,'Papaya',20,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(2006,2000,'Mango',50,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(2007,2000,'PineApple',15,20)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(2008,2000,'Pomegranate',20,12)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(2009,2000,'Guava',20,4)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(3001,3000,'Banana',20,1)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(3002,3000,'Orange',20,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(3003,3000,'Apple',25,5)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(3004,3000,'Watermelon',25,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(3005,3000,'Papaya',20,8)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(3006,3000,'Mango',20,15)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(3007,3000,'PineApple',25,20)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(3008,3000,'Pomegranate',20,12)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(3009,3000,'Guava',20,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(4001,4000,'Banana',50,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(4002,4000,'Orange',20,1)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(4003,4000,'Apple',50,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(4004,4000,'Watermelon',50,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(4005,4000,'Papaya',50,8)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(4006,4000,'Mango',50,15)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(4007,4000,'PineApple',50,20)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(4008,4000,'Pomegranate',50,12)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(4009,4000,'Guava',50,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(5001,5000,'Banana',100,1)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(5002,5000,'Orange',100,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(5003,5000,'Apple',100,5)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(5004,5000,'Watermelon',100,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(5005,5000,'Papaya',100,8)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(5006,5000,'Mango',100,15)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(5007,5000,'PineApple',100,20)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(5008,5000,'Pomegranate',100,12)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(5009,5000,'Guava',100,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(6001,6000,'Banana',20,1)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(6002,6000,'Orange',20,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(6003,6000,'Apple',25,5)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(6004,6000,'Watermelon',25,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(6005,6000,'Papaya',20,8)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(6006,6000,'Mango',20,15)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(6007,6000,'PineApple',25,20)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(6008,6000,'Pomegranate',20,12)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(6009,6000,'Guava',20,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(7001,7000,'Banana',50,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(7002,7000,'Orange',20,1)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(7003,7000,'Apple',50,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(7004,7000,'Watermelon',50,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(7005,7000,'Papaya',50,8)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(7006,7000,'Mango',50,15)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(7007,7000,'PineApple',50,20)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(7008,7000,'Pomegranate',50,12)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(7009,7000,'Guava',50,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(8001,8000,'Banana',20,1)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(8002,8000,'Orange',10,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(8003,8000,'Apple',15,5)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(8004,8000,'Watermelon',25,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(8005,8000,'Papaya',20,8)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(8006,8000,'Mango',50,15)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(8007,8000,'PineApple',15,20)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(8008,8000,'Pomegranate',20,12)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(8009,8000,'Guava',20,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(9001,9000,'Banana',20,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(9002,9000,'Orange',10,1)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(9003,9000,'Apple',15,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(9004,9000,'Watermelon',25,15)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(9005,9000,'Papaya',20,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(9006,9000,'Mango',50,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(9007,9000,'PineApple',15,20)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(9008,9000,'Pomegranate',20,12)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(9009,9000,'Guava',20,4)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(10001,10000,'Banana',100,1)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(10002,10000,'Orange',100,2)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(10003,10000,'Apple',100,5)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(10004,10000,'Watermelon',100,10)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(10005,10000,'Papaya',100,8)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(10006,10000,'Mango',100,15)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(10007,10000,'PineApple',100,20)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(10008,10000,'Pomegranate',100,12)")
mycursor.execute("INSERT INTO retailer_cart (product_id,store_id,item,quantity,price) VALUES(10009,10000,'Guava',100,2)")
mydb.commit()
print("Data inserted")



  
    
                  

     
